import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {createEntry,updateEntry,listEntries,saveSummary} from '../lib/store.ts';
function setup(){const sql=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));const db={prepare(query){let args=[];const statement=sql.prepare(query);const wrapper={bind(...values){args=values;return wrapper;},async run(){const result=statement.run(...args);return {meta:{changes:Number(result.changes)}};},async first(){return statement.get(...args)??null;},async all(){return {results:statement.all(...args)};}};return wrapper;}};return {sql,db};}
const value=(n=0)=>({id:`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,recordedAt:'2026-09-01T14:59:58.789Z',score:2,note:'元の投稿',tags:['睡眠']});
test('実SQL: 編集しても原日時・日付・旧疼痛を保持し、利用者を分離',async()=>{const {db,sql}=setup();const original=await createEntry(db,'a',value());sql.prepare('UPDATE entries SET pain=7 WHERE user_id=?').run('a');const changed=await updateEntry(db,'a',{...value(),recordedAt:'2026-09-18T00:00:00Z',score:4,note:'追記'});assert.equal(changed.recordedAt,original.recordedAt);assert.equal(changed.date,original.date);assert.equal(sql.prepare('SELECT pain FROM entries').get().pain,7);assert.equal(changed.score,4);assert.equal(await updateEntry(db,'b',{...value(),score:1}),null);assert.equal((await listEntries(db,'b',new URLSearchParams())).entries.length,0);});
test('実SQL: 再送は同じIDの投稿を複製・上書きしない',async()=>{const {db}=setup();await createEntry(db,'a',value());const again=await createEntry(db,'a',{...value(),note:'別の内容'});assert.equal(again.note,'元の投稿');assert.equal((await listEntries(db,'a',new URLSearchParams())).entries.length,1);});
test('実SQL: 同一時刻の85件を欠落・重複なくページングし、タグ・日付・文字で検索',async()=>{const {db}=setup();for(let n=0;n<85;n++)await createEntry(db,'a',{...value(n),note:n===12?'100% の確認':'メモ',tags:n===12?['単独']:['睡眠']});const first=await listEntries(db,'a',new URLSearchParams());const second=await listEntries(db,'a',new URLSearchParams({cursor:first.nextCursor}));const third=await listEntries(db,'a',new URLSearchParams({cursor:second.nextCursor}));assert.equal(first.entries.length,40);assert.equal(second.entries.length,40);assert.equal(third.entries.length,5);assert.equal(third.nextCursor,null);assert.equal(new Set([...first.entries,...second.entries,...third.entries].map(e=>e.id)).size,85);assert.equal((await listEntries(db,'a',new URLSearchParams({q:'%'}))).entries.length,1);assert.equal((await listEntries(db,'a',new URLSearchParams({tag:'単独',date:'2026-09-01'}))).entries.length,1);assert.equal((await listEntries(db,'a',new URLSearchParams({tag:'独'}))).entries.length,0);});
test('実SQL: 日別総括は日と利用者ごとに1件、作成日時を保持、投稿と独立',async()=>{const {db,sql}=setup();await createEntry(db,'a',value());await saveSummary(db,'a',{date:'2026-09-01',score:5,note:'一日全体'});sql.prepare('UPDATE daily_summaries SET created_at=? WHERE user_id=?').run('2026-09-02T00:00:00.123Z','a');await saveSummary(db,'a',{date:'2026-09-01',score:4,note:'追記'});await saveSummary(db,'b',{date:'2026-09-01',score:1,note:'別ユーザー'});const rows=sql.prepare('SELECT * FROM daily_summaries WHERE user_id=?').all('a');assert.equal(rows.length,1);assert.equal(rows[0].created_at,'2026-09-02T00:00:00.123Z');assert.equal(rows[0].score,4);assert.equal((await listEntries(db,'a',new URLSearchParams())).entries[0].score,2);});
test('実SQL: 数量の保存・編集・旧記録の既定値と再送の冪等性',async()=>{const {db,sql}=setup();const first=await createEntry(db,'a',{...value(),quantities:{睡眠:2.5}});assert.equal(first.quantities.睡眠,2.5);assert.equal((await createEntry(db,'a',{...value(),quantities:{睡眠:4}})).quantities.睡眠,2.5);const changed=await updateEntry(db,'a',{...value(),quantities:{睡眠:1}});assert.equal(changed.quantities.睡眠,1);assert.equal(changed.recordedAt,first.recordedAt);sql.prepare('INSERT INTO entries(id,user_id,date,recorded_at,score,note,tags,updated_at) VALUES (?,?,?,?,?,?,?,?)').run('legacy','a','2026-09-01',first.recordedAt,3,'','["旧タグ"]',first.recordedAt);const old=(await listEntries(db,'a',new URLSearchParams({tag:'旧タグ'}))).entries[0];assert.equal(old.quantities.旧タグ??1,1);});
