import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {catalogSchema,defaultCatalog,mergeCatalog,frequentTags} from '../lib/tags.ts';
import {readCatalog,writeCatalog} from '../lib/tag-store.ts';
function setup(){const sql=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));const db={prepare(query){let args=[];const st=sql.prepare(query);const w={bind(...v){args=v;return w;},async run(){return {meta:{changes:Number(st.run(...args).changes)}};},async first(){return st.get(...args)??null;},async all(){return {results:st.all(...args)};}};return w;}};return{db,sql};}
test('一タグ一グループと予約グループ名を検証し、旧タグは未分類へ',()=>{const c=defaultCatalog();assert.ok(catalogSchema.safeParse(c).success);assert.equal(catalogSchema.safeParse({...c,tags:[...c.tags,c.tags[0]]}).success,false);assert.equal(catalogSchema.safeParse({...c,groups:[...c.groups,'よく使うタグ']}).success,false);assert.equal(catalogSchema.safeParse({...c,tags:[{...c.tags[0],group:'存在しない'}]}).success,false);assert.equal(mergeCatalog(c,['旧タグ']).tags.at(-1).group,'未分類');});
test('頻出タグは回数順の重複表示で所属グループは変えない・非表示は除外',()=>{const c=defaultCatalog(), before=JSON.stringify(c);const tags=frequentTags(c,{服薬:4,睡眠:8,外出:2});assert.deepEqual(tags.map(t=>t.name),['睡眠','服薬','外出']);assert.equal(JSON.stringify(c),before);c.tags.find(t=>t.name==='睡眠').archived=true;assert.equal(frequentTags(c,{睡眠:8}).length,0);});
test('実SQL: タグ管理の永続化・利用者分離・競合防止・頻度は数量ではなく記録数',async()=>{const {db,sql}=setup();const c=defaultCatalog();const saved=await writeCatalog(db,'a',c);assert.equal(saved.catalog.revision,1);assert.equal(await writeCatalog(db,'a',c),null);const changed=await writeCatalog(db,'a',{...saved.catalog,groups:[...c.groups,'試験']});assert.equal(changed.catalog.revision,2);assert.ok((await readCatalog(db,'a')).catalog.groups.includes('試験'));assert.equal((await readCatalog(db,'b')).catalog.groups.includes('試験'),false);sql.prepare('INSERT INTO entries(id,user_id,date,recorded_at,note,tags,quantities,updated_at) VALUES (?,?,?,?,?,?,?,?)').run('1','a','2026-09-01','2026-09-01T00:00:00Z','','["服薬"]','{"服薬":10}','2026-09-01T00:00:00Z');assert.equal((await readCatalog(db,'a')).usage.服薬,1);assert.equal((await readCatalog(db,'b')).usage.服薬,undefined);});

test('実SQL: 最近のタグは頻度と独立し、利用者ごとに記録日時の降順',async()=>{const {db,sql}=setup();const st=sql.prepare('INSERT INTO entries(id,user_id,date,recorded_at,note,tags,updated_at) VALUES (?,?,?,?,?,?,?)');for(const [id,user,date,tags] of [['1','a','2026-09-01','["服薬"]'],['2','a','2026-09-02','["服薬"]'],['3','a','2026-09-03','["外出"]'],['4','b','2026-09-04','["睡眠"]']])st.run(id,user,date,date+'T00:00:00Z','',tags,date+'T00:00:00Z');const data=await readCatalog(db,'a');assert.deepEqual(data.recent,['外出','服薬']);assert.equal(data.usage.服薬,2);assert.deepEqual((await readCatalog(db,'b')).recent,['睡眠']);});
