'use client';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Bookmark, ChevronRight, EyeOff, FlaskConical, RotateCcw, Clock3 } from 'lucide-react';
import { type Overview } from '@/lib/journal';
import { type AnalysisSource } from '@/lib/insights';
import { patternAnalysis, type Sample } from '@/lib/patterns';
import { useRequest, dateText, fmt } from './shared';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const signed=(n:number|null)=>n===null?'—':`${n>0?'+':''}${n.toFixed(2)}`;
const topics=[['around','タグの前後'],['conditions','条件による違い'],['recovery','回復まで'],['stability','安定度'],['sequence','順序と連続'],['similar','似た日の続き']] as const;
type Topic=typeof topics[number][0];
type Props={overview:Overview;start:string;end:string;source:AnalysisSource;active:boolean;tag:string;onTag:(tag:string)=>void;onInspect:(tag:string,lag:number)=>void;onViewEntries:(date:string)=>void;demo:boolean};
type Disposition='saved'|'hidden'|'later';
const EMPTY_SAMPLES:Sample[]=[];
export function PatternLab({overview,start,end,source,active,tag,onTag,onInspect,onViewEntries,demo}:Props){
    const request=useRequest(), [state,setState]=useState<{key:string;overview:Overview;samples:Sample[];error:string}|null>(null),[attempt,setAttempt]=useState(0),[topic,setTopic]=useState<Topic>('around'),[partner,setPartner]=useState('');
    const storageKey=`shizuku-discoveries-v1-${demo?'demo':'own'}`;
    const [dispositions,setDispositions]=useState<Record<string,Disposition>>(()=>{try {const value=JSON.parse(localStorage.getItem(storageKey)||'{}');return value && typeof value === 'object' && !Array.isArray(value) ? Object.fromEntries(Object.entries(value).filter(([id,v])=>{try {const key=JSON.parse(id);return Array.isArray(key)&&key.length===3&&['moment','summary'].includes(key[0])&&typeof key[1]==='string'&&[1,3,7].includes(key[2])&&['saved','hidden','later'].includes(v as string);}catch{return false;}})) as Record<string,Disposition> : {};}catch{return {};}});
    const first=overview.days[0]?.date??end, from=start==='0000'?first:start,key=`${from}/${end}/${attempt}`;
    useEffect(()=>{
        if(!active)return;
        const controller=new AbortController();let current=true;
        request<{samples:Sample[]}>(`/api/analysis-records?${new URLSearchParams({start:from,end})}`,{signal:controller.signal}).then(r=>{if(current)setState({key,overview,samples:r.samples,error:''});}).catch(e=>{if(current)setState({key,overview,samples:[],error:(e as Error).message});});
        return()=>{current=false;controller.abort();};
    },[active,overview,from,end,key,request,attempt]);
    const ready=state?.key===key&&state.overview===overview;
    const samples=ready?state.samples:EMPTY_SAMPLES;
    const names=useMemo(()=>[...new Set(overview.days.filter(d=>d.date>=from&&d.date<=end).flatMap(d=>d.tags))].sort((a,b)=>a.localeCompare(b,'ja')),[overview,from,end]);
    const second=names.includes(partner)&&partner!==tag?partner:names.find(n=>n!==tag)??'';
    const data=useMemo(()=>patternAnalysis(overview,samples,from,end,source,tag,second),[overview,samples,from,end,source,tag,second]);
    function remember(id:string,value:Disposition|null){const next={...dispositions};if(value)next[id]=value;else delete next[id];setDispositions(next);try{localStorage.setItem(storageKey,JSON.stringify(next));}catch{}}
    const discoveryId=(t:string,l:number)=>JSON.stringify([source,t,l]);
    const saved=Object.entries(dispositions).filter(([,v])=>v==='saved');
    return <div className="pattern-lab">
      <section className="discovery-inbox analysis-card" aria-label="発見の受信箱">
        <div className="section-heading"><div><p className="insight-kicker">自分について、ひとつ知る</p><h2>発見の受信箱</h2></div><FlaskConical size={22}/></div>
        <p className="form-hint">前半で見つけた候補を、後半の記録で確かめます。探索中の手がかりです。</p>
        {data.inbox.candidates.filter(c=>!['hidden','later'].includes(dispositions[discoveryId(c.tag,c.lag)])).map(c=>{
          const id=discoveryId(c.tag,c.lag),r=c.confirmation;
          return <article className="discovery-card" key={id}>
            <span className={`discovery-status ${c.status}`}>{c.status==='consistent'?'後半も同じ方向':c.status==='different'?'後半では続かなかった':'後半の記録を待っています'}</span>
            <h3>「{c.tag}」を記録した{c.lag===1?'翌日':`${c.lag}日後`}</h3>
            <p>近い体調のタグなし日と比べた変化差</p>
            <div className="discovery-numbers"><span>前半 <b>{signed(c.train.diff)}</b><small>{c.train.withCount} / {c.train.withoutCount}日</small></span><ArrowRight size={18}/><span>後半 <b>{r.enough?signed(r.diff):'—'}</b><small>{r.withCount} / {r.withoutCount}日</small></span></div>
            <p className="form-hint">{c.status==='consistent'?'方向は共通しています。ほかの条件も見てみましょう。':c.status==='different'?'期間で違いがあります。いつでも同じとは限らない、という手がかり。':'タグあり・なしがそれぞれ5日そろうまで判断を保留します。'}</p>
            <div className="discovery-actions"><button className="text-button" onClick={()=>onInspect(c.tag,c.lag)}>比較を詳しく <ChevronRight size={15}/></button><button className="icon-button" aria-label={`${c.tag}の発見を${dispositions[id]==='saved'?'保存解除':'保存'}`} aria-pressed={dispositions[id]==='saved'} onClick={()=>remember(id,dispositions[id]==='saved'?null:'saved')}><Bookmark size={17}/></button><button className="icon-button" aria-label={`${c.tag}の発見を保留`} onClick={()=>remember(id,'later')}><Clock3 size={17}/></button><button className="icon-button" aria-label={`${c.tag}の発見を非表示`} onClick={()=>remember(id,'hidden')}><EyeOff size={17}/></button></div>
            <Evidence dates={[...c.train.dates,...r.dates]} onView={onViewEntries}/>
          </article>;
        })}
        {!data.inbox.candidates.length&&<div className="pattern-empty"><h3>{data.inbox.split?'無理に発見を作らず、記録を待つ。':'記録がたまると、ここに手がかりが届きます。'}</h3><p>{data.inbox.split?'前半では、比較可能で0.3点以上の差がある候補はありませんでした。':'候補の探索には、投稿がある日が30日以上必要です。下の分析は今ある記録で試せます。'}</p></div>}
        {!!Object.keys(dispositions).length&&<details className="pattern-method"><summary>保存・保留・非表示を管理（保存 {saved.length}件）</summary>{Object.entries(dispositions).map(([id,value])=>{let parts:string[];try{parts=JSON.parse(id);}catch{return null;}return <div className="disposition-row" key={id}><span>{parts[1]} · {parts[2]}日後 <small>{parts[0]==='summary'?'総括':'投稿平均'} / {value==='saved'?'保存':value==='later'?'保留':'非表示'}</small></span><button className="text-button" aria-label={`${parts[1]}の発見の整理を解除`} onClick={()=>remember(id,null)}><RotateCcw size={15}/>解除</button></div>;})}</details>}
        {data.inbox.split&&<p className="insight-footnote">{data.inbox.split}以降を確認期間に使用。探索した{data.inbox.tested}組から前半だけで最大2件を選択。日数はタグあり / なし。偶然の一致を除いた統計的な確証ではありません。</p>}
      </section>
      <section className="analysis-card pattern-explorer" aria-label="記録を深く調べる">
        <div className="section-heading"><h2>気になることから、調べる</h2><span className="metadata">試験機能</span></div>
        <Select value={topic} onValueChange={v=>setTopic(v as Topic)}><SelectTrigger aria-label="調べたいこと"><SelectValue/></SelectTrigger><SelectContent>{topics.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select>
        {['around','conditions','sequence'].includes(topic)&&<div className="pattern-tag-select"><label>対象のタグ<Select value={names.includes(tag)?tag:undefined} onValueChange={onTag}><SelectTrigger aria-label="詳しく調べるタグ"><SelectValue placeholder="タグを選ぶ"/></SelectTrigger><SelectContent>{names.map(n=><SelectItem key={n} value={n}>{n}</SelectItem>)}</SelectContent></Select></label></div>}
        {!ready?<p className="pattern-loading" role="status">時刻付きの記録を読み込んでいます…</p>:state.error?<div className="error-banner" role="alert">{state.error}<button onClick={()=>setAttempt(a=>a+1)}>再試行</button></div>:<>
        {topic==='around'&&<><h3>タグを残した前後に、何が起きた？</h3><p className="form-hint">「{tag||'タグ'}」の一日最初の投稿を起点に、実際に記録された体調を重ねます。{data.trajectory.events}日が対象。</p><Trajectory points={data.trajectory.points}/><div className="pattern-observations">{data.trajectory.points.map(p=><div key={p.hours}><span>{p.label}</span><strong>{p.actual.count>=3?fmt(p.actual.mean):'—'}<small>/5</small></strong><small>{p.actual.count}日</small></div>)}</div><details className="pattern-method"><summary>近い体調・時間帯の比較日と比べる</summary><p>起点の体調が同じで、6時間区分の時間帯が同じタグなし日を使います。</p>{data.trajectory.points.filter(p=>p.hours>0).map(p=><div className="pattern-result-row" key={p.hours}><span>{p.label}<small>タグあり {p.matched} / 比較 {p.controls}日</small></span><b>{signed(p.difference)}点</b></div>)}</details><Evidence dates={data.trajectory.points.find(p=>p.hours===0)?.dates??[]} onView={onViewEntries}/><p className="insight-footnote">各点3日以上で平均を表示。直前は過去2時間以内、1・3・6・24時間後はそれぞれ±0.5・1・2・3時間の最寄りの投稿。横軸は時点を等間隔に並べたものです。点ごとに対象日が異なります。他のタグや追加の行動は混ざり得ます。</p></>}
        {topic==='conditions'&&<><h3>同じタグでも、条件で違う？</h3><p className="form-hint">条件に当てはまる日の中で、当日の体調をそろえて翌日の変化差を比較。{source==='summary'?'一日の総括':'投稿の日平均'}を使用します。</p>{data.conditions.map(c=><details className="condition-result" key={c.label}><summary><span>{c.label}<small>タグあり {c.withCount} / 比較 {c.withoutCount}日</small></span><b>{c.enough?`${signed(c.diff)}点`:'比較不足'}</b></summary><p>タグありの変化 {signed(c.actual.mean)}点 / 比較日の変化 {signed(c.comparison)}点</p><Evidence dates={c.dates} onView={onViewEntries}/></details>)}<p className="insight-footnote">両側5日以上で表示。同時タグは頻出上位6種類まで。条件同士の差や相互作用を検定した数値ではありません。</p></>}
        {topic==='recovery'&&<><h3>低調から「ふつう」に戻るまで</h3><p className="form-hint">体調1〜2の投稿から、次に3以上を記録するまで。回復した瞬間を決めつけず、時間の幅で示します。</p><div className="pattern-kpis"><div><strong>{data.recovery.confirmed}</strong><span>3以上を確認</span></div><div><strong>{data.recovery.unresolved}</strong><span>追跡が途切れた・未確認</span></div></div>{!data.recovery.episodes.length?<p className="pattern-empty">この期間には体調1〜2の投稿がありません。</p>:<div className="recovery-list">{data.recovery.episodes.slice(-12).reverse().map(e=><button key={e.start} onClick={()=>onViewEntries(e.date)}><span>{dateText(e.date)}<small>{new Date(e.start).toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'})}から</small></span><b>{e.upper===null?'未確認':`${fmt(e.lower)}〜${fmt(e.upper)}時間`}</b><ChevronRight size={15}/></button>)}</div>}<p className="insight-footnote">最近12区間を表示。6時間超の空白、開始から24時間、集計期間の終端で追跡を止めます。未確認を回復なしと数えたり、確認できた例だけで平均回復時間を作ったりしません。</p></>}
        {topic==='stability'&&<><h3>平均は同じでも、過ごし方は違う。</h3><p className="form-hint">棒はその日の最低〜最高、点は平均。広いほど、記録された体調の幅が大きい日です。</p><div className="stability-list">{data.stability.filter(d=>d.count>=2).slice(-14).map(d=><button key={d.date} onClick={()=>onViewEntries(d.date)}><span>{d.date.slice(5).replace('-','/')}<small>{d.count}件</small></span><span className="stability-track"><i style={{left:`${(d.low-1)*25}%`,width:`${(d.high-d.low)*25}%`}}/><b style={{left:`${(d.average-1)*25}%`}}/></span><strong>{fmt(d.average)}<small>{d.low}〜{d.high}</small></strong></button>)}</div>{!data.stability.some(d=>d.count>=2)&&<p className="pattern-empty">同じ日に2件以上記録すると、変化幅を比較できます。</p>}<div className="pattern-scale"><span>1 · つらい</span><span>5 · 良い</span></div><details className="pattern-method"><summary>短い間隔での変化も見る</summary><p>同じ日の3時間以内の隣接投稿の差の絶対値。記録間隔が違う日の単純な順位付けはしません。</p>{data.stability.filter(d=>d.pairs).slice(-7).map(d=><div className="pattern-result-row" key={d.date}><span>{d.date}<small>{d.pairs}組 / 標準偏差 {fmt(d.sd)}</small></span><b>{fmt(d.step)}点</b></div>)}</details><p className="insight-footnote">直近14日分の観測日。記録のない時間の体調や、「良かった時間の長さ」は推定していません。</p></>}
        {topic==='sequence'&&<><h3>順番や、連日かどうかで変わる？</h3><label className="pattern-tag-select">組み合わせるタグ<Select value={second||undefined} onValueChange={setPartner}><SelectTrigger aria-label="順序を比較する相手タグ"><SelectValue placeholder="別のタグが必要です"/></SelectTrigger><SelectContent>{names.filter(n=>n!==tag).map(n=><SelectItem key={n} value={n}>{n}</SelectItem>)}</SelectContent></Select></label><Comparison title="一日の中の順序" first={`${tag} → ${second||'別タグ'}`} second={`${second||'別タグ'} → ${tag}`} result={data.sequence.order} onView={onViewEntries}/><p className="insight-footnote">各タグの最初の記録時刻で判定。同時刻の{data.sequence.tied}日は順序不明として除外。</p><Comparison title="連日の記録" first="前日も同じタグ" second="前日はタグなし" result={data.sequence.consecutive} onView={onViewEntries}/><p className="insight-footnote">どちらも翌日の体調 − 当日の体調。両側5日以上で差を表示。前日の投稿がない日は連日比較に含めません。起点の体調や行動量は調整していないため、まず元の記録で確かめるための比較です。</p></>}
        {topic==='similar'&&<><h3>似た日のあと、自分はどうなった？</h3>{data.similar.anchor?<><p className="form-hint">対象はこの期間で最後に体調がある{dateText(data.similar.anchor.date)}。平均 {fmt(data.similar.anchor.score)}、タグの重なりが近い過去の日を最大5件表示。</p>{data.similar.matches.length?<div className="similar-days">{data.similar.matches.map(m=><article key={m.date}><button className="text-button" onClick={()=>onViewEntries(m.date)}>{m.date}<ChevronRight size={15}/></button><div className="similar-scores"><strong>{fmt(m.score)}</strong><ArrowRight size={18}/><strong>{fmt(m.after)}</strong><small>翌日</small></div><p>{m.tags.length?m.tags.join(' · '):'タグなし'}</p><button className="text-button" onClick={()=>onViewEntries(m.nextDate)}>翌日の記録を見る</button></article>)}</div>:<p className="pattern-empty">翌日の体調までそろった、近い過去の日はまだありません。</p>}</>:<p className="pattern-empty">体調の記録が増えると、似た日を探せます。</p>}<p className="insight-footnote">体調差とタグ集合の不一致を合計して近い順に選択。候補もその翌日も対象日より過去に限定しています。次の体調を予測するモデルではありません。</p></>}
        <p className="pattern-data-count">時刻付きの投稿 {samples.length.toLocaleString()}件 · {from}〜{end}</p>
        </>}
      </section>
    </div>;
}
function Evidence({dates,onView}:{dates:string[];onView:(date:string)=>void}){const unique=[...new Set(dates)].sort().reverse();return unique.length?<details className="pattern-evidence"><summary>根拠の記録を読む <span>{unique.length}日</span></summary><div>{unique.slice(0,30).map(d=><button className="text-button" key={d} onClick={()=>onView(d)}>{d}<ChevronRight size={13}/></button>)}</div>{unique.length>30&&<p>直近30日を表示しています。</p>}</details>:null;}
function Comparison({title,first,second,result,onView}:{title:string;first:string;second:string;result:ReturnType<typeof patternAnalysis>['sequence']['order'];onView:(date:string)=>void}){return <div className="sequence-comparison"><h4>{title}</h4><div className="pattern-kpis"><div><span>{first}</span><strong>{result.first.count>=3?signed(result.first.mean):'—'}</strong><small>{result.first.count}日</small></div><div><span>{second}</span><strong>{result.second.count>=3?signed(result.second.mean):'—'}</strong><small>{result.second.count}日</small></div></div><p>翌日の変化の差 <b>{result.enough?`${signed(result.diff)}点`:'比較不足'}</b></p><Evidence dates={result.dates} onView={onView}/></div>;}
function Trajectory({points}:{points:ReturnType<typeof patternAnalysis>['trajectory']['points']}){const usable=points.map(p=>p.actual.count>=3?p.actual.mean:null),x=(i:number)=>30+i*53,y=(v:number)=>145-(v-1)*30;return <svg className="trajectory-chart" viewBox="0 0 325 180" role="img" aria-label="タグの前後の平均体調。縦軸は1から5、横軸は直前・記録時・1・3・6・24時間後。各点の数値は下に表示。">{[1,3,5].map(v=><g key={v}><line x1="25" x2="306" y1={y(v)} y2={y(v)} stroke="currentColor" opacity=".12"/><text x="8" y={y(v)+4}>{v}</text></g>)}{usable.map((v,i)=>v!==null?<g key={i}>{i>0&&usable[i-1]!==null&&<line x1={x(i-1)} y1={y(usable[i-1]!)} x2={x(i)} y2={y(v)} stroke="var(--primary)" strokeWidth="2.5"/>}<circle cx={x(i)} cy={y(v)} r="5" fill={v>=3.5?'#81cba1':v<2.5?'#d98a9e':'#a9b5d3'}/></g>:null)}{points.map((p,i)=><text key={p.hours} x={x(i)} y="170" textAnchor="middle">{['直前','記録時','1h','3h','6h','24h'][i]}</text>)}</svg>;}
