'use client';
import { useState } from 'react';
import { FolderPlus, Plus, Archive, RotateCcw, Pencil } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { type Catalog, type TagDefinition, UNGROUPED, FREQUENT, frequentTags } from '@/lib/tags';
export function TagManager({ catalog, usage, busy, onSave }: { catalog: Catalog; usage: Record<string, number>; busy: boolean; onSave: (c: Catalog) => Promise<boolean> }) {
    const [group, setGroup] = useState(''), [selected, setSelected] = useState<string | null>(null), [groupName, setGroupName] = useState(''), [editing, setEditing] = useState<TagDefinition | null>(null), [isNew, setIsNew] = useState(false), [showArchived, setShowArchived] = useState(false);
    const editTag = (t?: TagDefinition) => { setIsNew(!t); setEditing(t ?? { name: '', group: catalog.groups[0], quantified: false, unit: '', archived: false }); };
    async function saveTag() { if (!editing) return; const next = { ...editing, name: editing.name.trim() }; if (await onSave({ ...catalog, tags: isNew ? [...catalog.tags, next] : catalog.tags.map(t => t.name === next.name ? next : t) })) setEditing(null); }
    async function addGroup() { if (await onSave({ ...catalog, groups: [...catalog.groups, group.trim()] })) setGroup(''); }
    async function renameGroup() { if (!selected) return; const name = groupName.trim(); if (await onSave({ ...catalog, groups: catalog.groups.map(g => g === selected ? name : g), tags: catalog.tags.map(t => t.group === selected ? { ...t, group: name } : t) })) setSelected(null); }
    async function removeGroup() { if (!selected) return; if (await onSave({ ...catalog, groups: catalog.groups.filter(g => g !== selected), tags: catalog.tags.map(t => t.group === selected ? { ...t, group: UNGROUPED } : t) })) setSelected(null); }
    return <><div className="page-heading"><div><p className="eyebrow">YOUR TAGS</p><h1>タグの管理</h1></div><button className="primary-button" disabled={busy} onClick={() => editTag()}><Plus size={17}/>タグを追加</button></div><p className="form-hint">タグの所属先は一つ。よく使うタグには、記録した回数の多いものが自動で並びます。</p>
    <section className="tag-manager-group"><h2>{FREQUENT}</h2><div className="managed-tags">{frequentTags(catalog, usage).map(t => <span className="tag-chip" key={t.name}>#{t.name}<small>{usage[t.name]}回</small></span>)}{!frequentTags(catalog, usage).length && <p className="metadata">タグ付きの記録が増えると表示されます。</p>}</div></section>
    <fieldset disabled={busy} className="tag-management"><form className="group-create" onSubmit={e => { e.preventDefault(); void addGroup(); }}><input className="text-input" aria-label="新しいグループ名" placeholder="新しいグループ名" maxLength={30} value={group} onChange={e => setGroup(e.target.value)}/><button className="secondary-button" disabled={!group.trim()}><FolderPlus size={18}/>追加</button></form>
    {catalog.groups.map(g => <section className="tag-manager-group" key={g}><div className="section-heading"><h2>{g}</h2>{g !== UNGROUPED && <button className="icon-button" aria-label={`${g}グループを編集`} onClick={() => { setSelected(g); setGroupName(g); }}><Pencil size={16}/></button>}</div><div className="managed-tags">{catalog.tags.filter(t => t.group === g && !t.archived).map(t => <button className="managed-tag" key={t.name} onClick={() => editTag(t)}><span>#{t.name}</span>{t.quantified && <small>数量 · {t.unit || '数値'}</small>}<Pencil size={14}/></button>)}{!catalog.tags.some(t => t.group === g && !t.archived) && <span className="metadata">タグはまだありません</span>}</div></section>)}
    <button className="text-button" onClick={() => setShowArchived(!showArchived)} aria-expanded={showArchived}><Archive size={16}/>非表示のタグ（{catalog.tags.filter(t => t.archived).length}）</button>{showArchived && <div className="managed-tags">{catalog.tags.filter(t => t.archived).map(t => <button className="managed-tag" key={t.name} onClick={() => void onSave({ ...catalog, tags: catalog.tags.map(x => x.name === t.name ? { ...x, archived: false } : x) })}>#{t.name}<RotateCcw size={15}/>戻す</button>)}</div>}</fieldset>
    <Dialog open={!!editing} onOpenChange={v => !v && !busy && setEditing(null)}><DialogContent className="journal-dialog"><DialogTitle>{isNew ? 'タグを追加' : 'タグを編集'}</DialogTitle><DialogDescription>数量を使うタグも、選択した時の初期値は1です。</DialogDescription>{editing && <form onSubmit={e => { e.preventDefault(); void saveTag(); }}><fieldset disabled={busy} className="tag-edit-fields"><label>タグ名<input className="text-input" aria-label="タグ名" value={editing.name} readOnly={!isNew} maxLength={30} onChange={e => setEditing({ ...editing, name: e.target.value })}/></label>{!isNew && <p className="form-hint">名前は過去の記録と共通です。別の名前は新しいタグとして追加できます。</p>}<label>所属グループ<select className="text-input" aria-label="所属グループ" value={editing.group} onChange={e => setEditing({ ...editing, group: e.target.value })}>{catalog.groups.map(g => <option key={g}>{g}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={editing.quantified} onChange={e => setEditing({ ...editing, quantified: e.target.checked })}/>数量・強度を入力する</label>{editing.quantified && <label>単位（任意）<input className="text-input" aria-label="数量の単位" placeholder="錠、回、強度など" maxLength={10} value={editing.unit} onChange={e => setEditing({ ...editing, unit: e.target.value })}/></label>}<div className="row">{!isNew && <button type="button" className="text-button" onClick={async () => { if (await onSave({ ...catalog, tags: catalog.tags.map(t => t.name === editing.name ? { ...t, archived: true } : t) })) setEditing(null); }}><Archive size={16}/>非表示にする</button>}<button className="primary-button" type="submit" disabled={!editing.name.trim()}>保存</button></div><p className="form-hint">非表示にしても過去の記録は残ります。</p></fieldset></form>}</DialogContent></Dialog>
    <Dialog open={!!selected} onOpenChange={v => !v && !busy && setSelected(null)}><DialogContent className="journal-dialog"><DialogTitle>グループを編集</DialogTitle><DialogDescription>グループを削除すると、中のタグは「未分類」に移ります。</DialogDescription><fieldset disabled={busy}><input className="text-input" aria-label="グループ名" value={groupName} maxLength={30} onChange={e => setGroupName(e.target.value)}/><div className="row"><button className="danger-button" onClick={() => void removeGroup()}>グループを削除</button><button className="primary-button" disabled={!groupName.trim()} onClick={() => void renameGroup()}>名前を保存</button></div></fieldset></DialogContent></Dialog></>;
}
