'use client';
import { useMemo, useState } from 'react';
import { TrendingUp } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { type Overview, tagAssociations, todayKey, shiftDay, mean } from '@/lib/journal';
import { fmt } from './shared';
export function Trends({ overview }: {
    overview: Overview;
}) {
    const [range, setRange] = useState('30'), [source, setSource] = useState('summary'), [mode, setMode] = useState<'same' | 'next'>('same');
    const start = range === 'all' ? '0000' : shiftDay(todayKey(), 1 - Number(range));
    const summaries = overview.summaries.filter(s => s.date >= start), days = overview.days.filter(d => d.date >= start);
    const associations = useMemo(() => tagAssociations(overview.days.filter(d => d.date >= start), mode, source === 'summary' ? overview.summaries.filter(s => s.date >= start) : undefined), [overview, start, mode, source]);
    const dates = Array.from({ length: 30 }, (_, i) => shiftDay(todayKey(), i - 29));
    return <><div className="page-heading"><div><p className="eyebrow">THE BIG PICTURE</p><h1>体調の流れ</h1></div><Select value={range} onValueChange={setRange}><SelectTrigger aria-label="集計する期間"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="7">最近の7日</SelectItem><SelectItem value="30">最近の30日</SelectItem><SelectItem value="90">最近の90日</SelectItem><SelectItem value="all">すべて</SelectItem></SelectContent></Select></div><div className="stat-grid"><section className="stat-card"><span>一日の総括</span><strong>{fmt(mean(summaries.map(s => s.score)))}<small>/ 5</small></strong><p>{summaries.length}日分の総括の平均</p></section><section className="stat-card"><span>その時の体調</span><strong>{fmt(mean(days.flatMap(d => d.score === null ? [] : [d.score])))}<small>/ 5</small></strong><p>日ごとの平均を、同じ重みで集計</p></section><section className="stat-card"><span>残した投稿</span><strong>{days.reduce((sum, d) => sum + d.count, 0)}<small>件</small></strong><p>{days.length}日分の足あと</p></section></div>
 <section className="chart-card"><div className="section-heading"><h2>一日の総括の推移</h2><span className="metadata">最近の30日</span></div>{overview.summaries.some(s => s.date >= dates[0]) ? <div className="chart"><svg viewBox="0 0 700 200" role="img" aria-label="最近30日間の一日の総括。1がとてもつらい、5が良い。未記録の日には線をつながない。">{[1, 3, 5].map(n => <g key={n}><line x1="25" x2="688" y1={166 - (n - 1) * 34} y2={166 - (n - 1) * 34} stroke="var(--border)"/><text x="3" y={170 - (n - 1) * 34} fill="var(--muted-foreground)" fontSize="13">{n}</text></g>)}{dates.map((d, i) => { const value = overview.summaries.find(s => s.date === d), prev = overview.summaries.find(s => s.date === dates[i - 1]), x = 26 + i * 22.7; return <g key={d}>{value && <>{prev && <line x1={x - 22.7} y1={166 - (prev.score - 1) * 34} x2={x} y2={166 - (value.score - 1) * 34} stroke="var(--primary)" strokeWidth="2.5"/>}<circle cx={x} cy={166 - (value.score - 1) * 34} r="4" fill="var(--primary)"><title>{d} 総括 {value.score}</title></circle></>}{(i % 7 === 0 || i === 29) && <text x={x} y="194" textAnchor={i === 29 ? 'end' : 'middle'} fontSize="13" fill="var(--muted-foreground)">{Number(d.slice(5, 7))}/{Number(d.slice(8))}</text>}</g>; })}</svg></div> : <div className="empty-state"><TrendingUp size={26}/><p>カレンダーに総括を残すと、ここに日々の流れが見えます。</p></div>}<p className="form-hint">カレンダーで入力した総括だけを表示。空白は未記録です。</p></section>
 <section className="analysis-card"><div className="section-heading"><div><h2>タグと体調の関連</h2><p className="form-hint">そのタグを残した日と、それ以外の日を比べます。</p></div></div><div className="analysis-controls"><Select value={source} onValueChange={setSource}><SelectTrigger aria-label="分析する体調"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="summary">一日の総括</SelectItem><SelectItem value="moment">その時の体調（日平均）</SelectItem></SelectContent></Select><Tabs value={mode} onValueChange={v => setMode(v as 'same' | 'next')}><TabsList><TabsTrigger value="same">同じ日</TabsTrigger><TabsTrigger value="next">翌日の変化</TabsTrigger></TabsList></Tabs></div><p className="analysis-explainer">{mode === 'same' ? 'タグありの日 − タグなしの日の体調差' : '「翌日 − 当日」の変化量を、タグあり・なしで比較'}</p>
 {associations.length ? associations.map(a => <div className="association-row" key={a.tag}><div><strong>#{a.tag}</strong><p>あり {a.withCount}日 · なし {a.withoutCount}日</p></div><div className="association-value">{a.enough && a.diff !== null ? <><b className={a.diff >= 0 ? 'positive' : 'negative'}>{a.diff > 0 ? '+' : ''}{a.diff.toFixed(2)}</b><span>/ 5</span></> : <span>記録を待っています</span>}</div></div>) : <div className="empty-state"><p>タグ付きの投稿が増えると、比較できるようになります。</p></div>}
 <p className="analysis-caveat">両方のグループが3日以上そろうと表示します。数字は記録上の関連で、因果効果ではありません。未記録の日は比較せず、翌日は連続する日だけを使います。</p></section></>;
}
